name: Build project
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    needs: natives
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Download natives
        uses: actions/download-artifact@v7
        with:
          path: natives
          pattern: natives-*
          merge-multiple: true

      - name: Build project
        run: ./gradlew --no-daemon -P prebuilt_natives=natives build

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          path: |
            build/libs/
            !build/libs/*-sources.jar
            !build/libs/*-all.jar

  natives:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build project
        run: ./gradlew --no-daemon compileNatives

      - name: Upload natives
        uses: actions/upload-artifact@v6
        with:
          path: build/natives/*
          name: natives-${{ matrix.os }}
